FROM ubuntu:latest
RUN apt-get update \
  && apt-get install -y wget
RUN wget --directory-prefix=/usr/lib https://github.com/project-alvarium/alvarium-sdk-go/raw/main/internal/iota/include/libiota_streams_c.so

WORKDIR /adam
COPY ./bin/ .

ENTRYPOINT ["./adam"]